### ISSUE TITLE
F1-Story 11 Client change profile info

### ISSUE THREAD

**Issue by sunero4** [sunero4/LunchBucks#35]

**Comment by DanielDKnudsen** [comment]
![20180906_174521014.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a81fef596cee2001232e1b0/125516c66e82c728ace21e0d46bac4cb7bd2daf9d9d6ee14f008a2c5791773316546b3397f8fe62bab0021435a0e49f8490e0947fbf1df2ca2e23c708b0f03e9d2685e26d42103eee9dc4be05ce36ade0d97bcae8b4bcae93826e0838e4f3d1901198efe4f78.jpg)

**Comment by DanielDKnudsen** [comment]
![blah.jpg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a81fef596cee2001232e1b0/125516c66e82c728ace21e0d46ea989b2bc0cfeb9ffbb049a15ee4d6730472727e00fb2d76d6b470b9152f055f5f4fff495c5c41fdab9b37b4f46d2ede0356b49b381d66cc2f10a4b2831abc06b2218b4b87b1bd8b45d2a5.jpg)

**Comment by DanielDKnudsen** [comment]
hsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsad

**Comment by TFJTFJ** [comment]
Det kniber lidt med de sigende commit-kommentarer...

Venligst
Troels


On 24 Sep 2018, at 19.34, DanielDKnudsen <notifications@github.com<mailto:notifications@github.com>> wrote:


hsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsadhsad

**Comment by DanielDKnudsen** [comment]
This issue was moved to sunero4/LunchBucksFrontEnd#2
